feature: use logging function with loglevel support

diff --git a/actions/action-common b/actions/action-common
--- a/actions/action-common
+++ b/actions/action-common
@@ -3,44 +3,68 @@
 # debug mode
 DEBUG=${DEBUG:-false}
 if [ "$DEBUG" == "true" ]; then
-    echo "-> Debugging mode enabled ..."
-    set -x
+  echo "-> Debugging mode enabled ..."
+  set -x
 fi
 
 # global variables
 MPI_RESOURCES_MIRROR=https://raw.githubusercontent.com/EnvCLI/modular-pipeline/master/resources
 
+# func: logging
+declare -A levels=([TRACE]=0 [DEBUG]=1 [INFO]=2 [WARN]=3 [ERROR]=4)
+function act-log-message() {
+  local log_message=$1
+  local log_priority=$2
+
+  # check if level exists
+  [[ ${levels[$log_priority]} ]] || return 1
+
+  # check if level is enough
+  (( ${levels[$log_priority]} < ${levels[${SCRIPT_LOG_LEVEL:-INFO}]} )) && return 0
+
+  # log the message
+  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ${log_priority} : ${log_message}"
+}
+
+# func: run
+function run-command() {
+  act-log-message "Command $*" "TRACE"
+  eval "$@"
+}
+
+# func: run in container
+function run-in-container() {
+  eval run-command envcli run "$@"
+}
+
 # func: prepare
-function act-common-prepare()
-{
+function act-common-prepare() {
   # source in .ci/env
   if [ -f ".ci/env" ]; then
-    if [ "${VERBOSE:-false}" == "true" ]; then
-      echo "-> loading environment from .ci/env"
-    fi
+    act-log-message "loading environment from .ci/env" "DEBUG"
     export $(grep -v '^#' .ci/env | xargs)
   fi
 
   # prerequisites
+  # - docker
+  if ! command -v docker > /dev/null; then
+    act-log-message "docker is required but missing!" "ERROR"
+    exit 1
+  fi
   # - envcli
   if ! command -v envcli > /dev/null; then
-    echo "-> envcli not available. Please run the modular pipeline installation script!"
+    act-log-message "-> envcli not available. Please run theinstallation script!" "ERROR"
     exit 1
   fi
   # - normalizeci
   if ! command -v normalizeci > /dev/null; then
-    echo "-> normalizeci not available. Please run the modular pipeline installation script!"
-    exit 1
-  fi
-  # - docker
-  if ! command -v docker > /dev/null; then
-    echo "-> docker not available. Please install docker!"
+    act-log-message "-> normalizeci not available. Please run the installation script!" "ERROR"
     exit 1
   fi
 
   # find container runtime (if docker info fails)
   if ! docker info &>/dev/null; then
-    echo "-> trying to find a working container runtime ..."
+    act-log-message "trying to find a working container runtime ..." "DEBUG"
 
     # set DOCKER_HOST
     set +u
@@ -48,26 +72,22 @@ function act-common-prepare()
     local CPORT=2375
 
     if [ -z "$DOCKER_HOST" ] && [ "$KUBERNETES_PORT" ]; then
-      echo "-> detected kubernetes usage, using localhost"
+      act-log-message "detected kubernetes usage, using localhost" "DEBUG"
       CHOST=localhost
     fi
     if [ "$DOCKER_TLS_CERTDIR" ]; then
-      echo "-> detected docker tls cert usage, using port 2376"
+      act-log-message "detected docker tls cert usage, using port 2376" "DEBUG"
       CPORT=2376
     fi
 
     export DOCKER_HOST="tcp://${CHOST}:${CPORT}"
     set -u
   else
-    if [ "${VERBOSE:-false}" == "true" ]; then
-      echo "-> container runtime is ready for use"
-    fi
+    act-log-message "container runtime is ready for use" "TRACE"
   fi
 
   # normalize ci variables
-  if [ "${VERBOSE:-false}" == "true" ]; then
-    echo "-> execute: normalizeci"
-  fi
+  act-log-message "run normalizeci" "TRACE"
   eval $(normalizeci)
 
   # ensure required variables are set
@@ -85,29 +105,9 @@ function act-common-prepare()
 # func: run hook / $1 = hook name
 function act-common-hook()
 {
-    # repository hooks
-    if test -f "$NCI_PROJECT_DIR/.ci/$1.sh"; then
-        echo "-> execute: repository hook \`$1\`"
-        $NCI_PROJECT_DIR/.ci/$1.sh
-    fi
-}
-
-# container registry login
-function act-common-container-registry-login()
-{
-  echo "-> trying to login to container registry $NCI_CONTAINERREGISTRY_HOST ..."
-
-  if [[ -n "$NCI_CONTAINERREGISTRY_USERNAME" ]]; then
-    docker login -u "$NCI_CONTAINERREGISTRY_USERNAME" -p "$NCI_CONTAINERREGISTRY_PASSWORD" "$NCI_CONTAINERREGISTRY_HOST"
-  else
-    echo "Failed to login to container registry! No credentials provided!"
-    exit 1
+  # repository hooks
+  if test -f "$NCI_PROJECT_DIR/.ci/$1.sh"; then
+    act-log-message "execute: repository hook [${1}]" "INFO"
+    $NCI_PROJECT_DIR/.ci/$1.sh
   fi
-}
-
-# container registry login
-function act-common-container-registry-push()
-{
-  echo "-> pushing image to remote registry $NCI_CONTAINERREGISTRY_HOST ..."
-  docker push "${1:-}"
 }
diff --git a/actions/action-common-kubernetes b/actions/action-common-kubernetes
--- a/actions/action-common-kubernetes
+++ b/actions/action-common-kubernetes
@@ -5,21 +5,21 @@ set -euo pipefail
 function act-common-kubernetes-ensure-namespace {
   local TARGET_NAMESPACE=${1:-}
   if [ -z "$TARGET_NAMESPACE" ]; then
-    echo "error: no target namespace specified as first argument when calling func act-common-kubernetes-ensure-namespace"
+    act-log-message "no target namespace specified as first argument when calling func act-common-kubernetes-ensure-namespace" "ERROR"
     exit 1
   fi
 
-  echo "-> making sure namespace $TARGET_NAMESPACE exists ..."
+  act-log-message "making sure namespace $TARGET_NAMESPACE exists ..." "DEBUG"
   set +e
-  envcli run kubectl get namespace "$TARGET_NAMESPACE"
-  getnamespace=$?
+  run-in-container kubectl get namespace "$TARGET_NAMESPACE" >> /dev/null
+  local getNamespaceStatus=$?
   set -e
-  if [ "$getnamespace" -ne "0" ]; then
+  if [ "$getNamespaceStatus" -ne "0" ]; then
     ## create namespace
-    echo "-> creating namespace $TARGET_NAMESPACE"
-    envcli run kubectl create namespace "$TARGET_NAMESPACE"
+    act-log-message "creating namespace $TARGET_NAMESPACE" "INFO"
+    run-in-container kubectl create namespace "$TARGET_NAMESPACE"
   else
-    echo "-> namespace exists. skipping creation ..."
+    act-log-message "namespace exists. skipping creation ..." "DEBUG"
   fi
 }
 
@@ -29,33 +29,33 @@ function act-common-kubernetes-download-chart
   local CHART_ID=${1:-}
 
   # prepare helm cli
-  echo " - Initializing Helm ..."
-  envcli run helm init --client-only --skip-refresh
+  act-log-message "Initializing Helm ..." "DEBUG"
+  run-in-container helm init --client-only --skip-refresh &> /dev/null
 
   # print variable content
   local CHART_REPOSITORY=$(echo $CHART_ID | cut -d '/' -f 1)
 
   # Check if the repository is known / needs to be added for the deployment to work
-  echo " - Chart Repository: ${CHART_REPOSITORY}"
+  act-log-message "Chart Repository: ${CHART_REPOSITORY}" "DEBUG"
   if [ "$CHART_REPOSITORY" != "stable" ]; then
     ## if the repo isn't stable/ then we're using a custom repository that we need to initialize
-    echo " - Using custom chart repository: ${CHART_REPOSITORY}"
+    act-log-message "Using custom chart repository: ${CHART_REPOSITORY}" "DEBUG"
 
     if [ "$CHART_REPOSITORY" == "incubator" ]; then
-      envcli run helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com &> /dev/null
+      run-in-container helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com &> /dev/null
     elif [ "$CHART_REPOSITORY" == "rancher-stable" ]; then
-      envcli run helm repo add rancher-stable https://releases.rancher.com/server-charts/stable &> /dev/null
+      run-in-container helm repo add rancher-stable https://releases.rancher.com/server-charts/stable &> /dev/null
     elif [ "$CHART_REPOSITORY" == "appscode" ]; then
-      envcli run helm repo add appscode https://charts.appscode.com/stable &> /dev/null
+      run-in-container helm repo add appscode https://charts.appscode.com/stable &> /dev/null
     elif [ "$CHART_REPOSITORY" == "gitlab" ]; then
-      envcli run helm repo add gitlab https://charts.gitlab.io &> /dev/null
+      run-in-container helm repo add gitlab https://charts.gitlab.io &> /dev/null
     elif [ "$CHART_REPOSITORY" == "jetstack" ]; then
-      envcli run helm repo add jetstack https://charts.jetstack.io &> /dev/null
+      run-in-container helm repo add jetstack https://charts.jetstack.io &> /dev/null
     elif [ "$CHART_REPOSITORY" == "philippheuer" ]; then
-      envcli run helm repo add philippheuer https://philippheuer.gitlab.io/kubernetes-charts &> /dev/null
+      run-in-container helm repo add philippheuer https://philippheuer.gitlab.io/kubernetes-charts &> /dev/null
     fi
   fi
-  envcli run helm repo update
+  run-in-container helm repo update &> /dev/null
 }
 
 # initialize tiller
@@ -63,26 +63,38 @@ function act-common-kubernetes-initialize-tiller
 {
   # check if tiller was already initialized
   set +e
-  kubectl get serviceaccount --namespace ${DEPLOY_NAMESPACE} tiller
-  getTillerServiceaccount=$?
+  run-in-container kubectl get serviceaccount --namespace ${DEPLOYMENT_NAMESPACE} tiller >> /dev/null
+  local getTillerServiceAccountStatus=$?
   set -e
-  if [ "$getTillerServiceaccount" -ne "0" ]; then
-    echo "--> Initializing Tiller"
+  if [ "$getTillerServiceAccountStatus" -ne "0" ]; then
+    act-log-message "Service account missing, creating tiller service account ..." "DEBUG"
+
     ## Service Account
-    envcli run kubectl create serviceaccount --namespace ${DEPLOY_NAMESPACE} tiller
+    run-in-container kubectl create serviceaccount --namespace ${DEPLOYMENT_NAMESPACE} tiller
 
     ## Service Account Permissions (namespace admin or cluster admin, depending on $DEPLOYMENT_CLUSTER_ADMIN)
     if [ "$DEPLOYMENT_CLUSTER_ADMIN" == "true" ]; then
-      echo "--> Granting tiller cluster admin role."
-      envcli run kubectl create clusterrolebinding ${DEPLOY_NAMESPACE}-tiller-rule --clusterrole=cluster-admin --serviceaccount=${DEPLOY_NAMESPACE}:tiller
+      act-log-message "Granting tiller cluster admin role." "INFO"
+      run-in-container kubectl create clusterrolebinding ${DEPLOYMENT_NAMESPACE}-tiller-rule \
+        --clusterrole=cluster-admin \
+        --serviceaccount=${DEPLOYMENT_NAMESPACE}:tiller
     else
-      echo "--> Granting tiller namespace admin role."
-      envcli run kubectl create rolebinding ${DEPLOY_NAMESPACE}-tiller-binding --namespace=${DEPLOY_NAMESPACE} --clusterrole=admin --serviceaccount=${DEPLOY_NAMESPACE}:tiller
+      act-log-message "Granting tiller namespace admin role." "INFO"
+      run-in-container kubectl create rolebinding ${DEPLOYMENT_NAMESPACE}-tiller-binding \
+        --namespace=${DEPLOYMENT_NAMESPACE} \
+        --clusterrole=admin \
+        --serviceaccount=${DEPLOYMENT_NAMESPACE}:tiller
     fi
 
     ## Install Tiller
-    envcli run helm init --service-account tiller --override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' --history-max 3 --upgrade --wait
+    run-in-container helm init \
+      --tiller-namespace "${DEPLOYMENT_NAMESPACE}" \
+      --service-account tiller \
+      --history-max 3 \
+      --upgrade \
+      --wait >> /dev/null
+    #--override 'spec.template.spec.containers[0].command'='{/tiller,--storage=secret}' \
   else
-    echo "Tiller is initialized. skipping setup ..."
+    act-log-message "Tiller is initialized. skipping setup ..." "DEBUG"
   fi
 }
diff --git a/actions/action-helm-deploy b/actions/action-helm-deploy
--- a/actions/action-helm-deploy
+++ b/actions/action-helm-deploy
@@ -18,57 +18,78 @@ function main()
   export DOCKER_DRIVER="${DOCKER_DRIVER:-overlay2}"
 
   # parameters
-  # - environment
-  local DEPLOYMENT_ENVIRONMENT=${1:-$DEPLOYMENT_ENVIRONMENT}
-  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
-    echo "error: no target environment specified when calling deploy stage!"
+  # - namespaces
+  local DEPLOYMENT_NAMESPACE=${1:-$DEPLOYMENT_NAMESPACE}
+  if [ -z "$DEPLOYMENT_NAMESPACE" ]; then
+    act-log-message "error: no deployment namespace specified! Plase set [DEPLOYMENT_NAMESPACE] or provide it as 1st argument when calling action-helm-deploy!" "ERROR"
     exit 1
   fi
+  # - deployment id
   local DEPLOYMENT_ID=${2:-$DEPLOYMENT_ID}
   if [ -z "$DEPLOYMENT_ID" ]; then
-    echo "error: no deployment id specified!"
+    act-log-message "no deployment id specified! Plase set [DEPLOYMENT_ID] or provide it as 2nd argument when calling action-helm-deploy!" "ERROR"
     exit 1
   fi
-  echo "-> deploying environment [$DEPLOYMENT_ENVIRONMENT - ID: $DEPLOYMENT_ID] ..."
-  # - namespaces
-  local DEPLOYMENT_NAMESPACE=${2:-$DEPLOYMENT_NAMESPACE}
-  if [ -z "$DEPLOYMENT_NAMESPACE" ]; then
-    echo "error: no deployment namespace specified!"
+  # - environment
+  local DEPLOYMENT_ENVIRONMENT=${3:-$DEPLOYMENT_ENVIRONMENT}
+  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
+    act-log-message "no target environment specified. Plase set [DEPLOYMENT_ENVIRONMENT] or provide it as 3rd argument when calling action-helm-deploy!" "ERROR"
     exit 1
   fi
-  export TILLER_NAMESPACE=${DEPLOYMENT_NAMESPACE}
+  act-log-message "deploying environment [$DEPLOYMENT_ENVIRONMENT - ID: $DEPLOYMENT_ID] ..." "DEBUG"
+
   # - access
   export DEPLOYMENT_CLUSTER_ADMIN=${DEPLOYMENT_CLUSTER_ADMIN:-"false"}
   if [[ -z "${KUBECONFIG_CONTENT:-}" ]]; then
-    echo "You need to provide a kubeconfig in the env variable KUBECONFIG_CONTENT to connect to your kubernetes cluster!"
+    act-log-message "Please encode your kubeconfig as base64 and set it as environment variable [KUBECONFIG_CONTENT] to allow the pipeline to access a k8s cluster!" "ERROR"
     return 1
   fi
+
   # - chart
-  local DEPLOYMENT_CHART=${DEPLOYMENT_CHART:-stable/wordpress} # todo: remove default
+  local DEPLOYMENT_CHART=${4:-$DEPLOYMENT_CHART}
+  if [ -z "$DEPLOYMENT_CHART" ]; then
+    act-log-message "error: no deployment chart specified! Plase set [DEPLOYMENT_CHART] or provide it as 4th argument when calling action-helm-deploy!" "ERROR"
+    exit 1
+  fi
   local DEPLOYMENT_CHART_VERSION=${DEPLOYMENT_CHART_VERSION:-}
 
   # download the chart / add the required repositories
-  act-common-kubernetes-download-chart $DEPLOYMENT_CHART
+  act-common-kubernetes-download-chart "$DEPLOYMENT_CHART"
 
   # make sure the target namespace exists
-  act-common-kubernetes-ensure-namespace $DEPLOYMENT_NAMESPACE
+  act-common-kubernetes-ensure-namespace "$DEPLOYMENT_NAMESPACE"
 
   # init tiller
-  act-common-kubernetes-initialize-tiller $DEPLOYMENT_NAMESPACE
+  act-common-kubernetes-initialize-tiller "$DEPLOYMENT_NAMESPACE"
 
   # generate deployment configuration
-  act-common-deploy-generate-configuration $DEPLOYMENT_ENVIRONMENT
+  act-common-deploy-generate-configuration "$DEPLOYMENT_ENVIRONMENT"
   # values.yaml -f .helm/default.yaml
 
-  # run deployment
+  # deploy the helm chart
+  #
+  # * tiller-namespace: the namespace helms service side component tiller runs in
+  # * namespace: the target namespace we deploy into
+  # * install: install the specified chart, if it is not deployed yet
+  # * force: overwrite conflicting resources if required (some have immutable attributes)
+  # * version: the version of the chart that should be used
+  #
+  act-log-message "deploying using chart [${DEPLOYMENT_CHART}:${DEPLOYMENT_CHART_VERSION:-latest}] into namespace [$DEPLOYMENT_NAMESPACE] as [$DEPLOYMENT_ID]" "INFO"
   if [ -z "${DEPLOYMENT_CHART_VERSION}" ]; then
-    ## without version
-    echo " - Deploying chart ${DEPLOYMENT_CHART} into ${DEPLOYMENT_NAMESPACE}"
-    envcli run helm upgrade --install --force --namespace ${DEPLOYMENT_NAMESPACE} $DEPLOY_SLUG ${DEPLOYMENT_CHART}
+    run-in-container helm upgrade \
+      --tiller-namespace "${DEPLOYMENT_NAMESPACE}" \
+      --namespace "${DEPLOYMENT_NAMESPACE}" \
+      --install \
+      --force \
+      "$DEPLOYMENT_ID" "${DEPLOYMENT_CHART}"
   else
-    ## with version
-    echo " - Deploying chart ${DEPLOYMENT_CHART} - ${DEPLOYMENT_CHART_VERSION} into ${DEPLOYMENT_NAMESPACE}"
-    envcli run helm upgrade --install --force --namespace ${DEPLOYMENT_NAMESPACE} --version ${DEPLOYMENT_CHART_VERSION} $DEPLOY_SLUG ${DEPLOYMENT_CHART}
+    run-in-container helm upgrade \
+      --tiller-namespace "${DEPLOYMENT_NAMESPACE}" \
+      --namespace "${DEPLOYMENT_NAMESPACE}" \
+      --version "${DEPLOYMENT_CHART_VERSION}" \
+      --install \
+      --force \
+      "$DEPLOYMENT_ID" "${DEPLOYMENT_CHART}"
   fi
 }
 
@@ -87,7 +108,7 @@ case "${1:-}" in
     echo "* DEPLOYMENT_CHART_VERSION: helm chart version, using latest by default."
     ;;
   *)
-    echo "Running action [$ACTION_CATEGORY.$ACTION_NAME]"
+    act-log-message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
     act-common-prepare
     act-common-hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
     main "$@"
diff --git a/actions/action-swarm-deploy b/actions/action-swarm-deploy
--- a/actions/action-swarm-deploy
+++ b/actions/action-swarm-deploy
@@ -7,24 +7,50 @@ ACTION_NAME="deploy"
 LOCAL_PATH=${BASH_SOURCE%/*}
 source "$LOCAL_PATH/action-common"
 source "$LOCAL_PATH/action-common-deploy"
+source "$LOCAL_PATH/action-common-container"
 
 # main
 function main()
 {
-  # configuration
-  local DEPLOYMENT_ENVIRONMENT=${1:-}
-  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
-    echo "error: no target environment specified when calling deploy stage!"
+  # namespace
+  local DEPLOYMENT_NAMESPACE=${1:-$DEPLOYMENT_NAMESPACE}
+  if [ -z "$DEPLOYMENT_NAMESPACE" ]; then
+    act-log-message "Required attribute DEPLOYMENT_NAMESPACE missing, set via env or pass it as 1st parameter to action-swarm-deploy!" "ERROR"
     exit 1
   fi
+
+  # deployment id
   local DEPLOYMENT_ID=${2:-$DEPLOYMENT_ID}
   if [ -z "$DEPLOYMENT_ID" ]; then
-    echo "error: no deployment id specified!"
+    act-log-message "Required attribute DEPLOYMENT_ID missing, set via env or pass it as 2nd parameter to action-swarm-deploy!" "ERROR"
     exit 1
   fi
-  echo "-> deploying environment [$DEPLOYMENT_ENVIRONMENT - ID: $DEPLOYMENT_ID] ..."
+
+  # environment
+  local DEPLOYMENT_ENVIRONMENT=${3:-$DEPLOYMENT_ENVIRONMENT}
+  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
+    act-log-message "Required attribute DEPLOYMENT_ENVIRONMENT missing, set via env or pass it as 3rd parameter to action-swarm-deploy!" "ERROR"
+    exit 1
+  fi
+
+  act-log-message "deploying environment [$DEPLOYMENT_ENVIRONMENT - ID: $DEPLOYMENT_ID] ..." "INFO"
+  export SWARMSTACKFILE=${SWARMSTACKFILE:-swarm.yml}
   export CONTAINER_REPO=${CONTAINER_REPO:-$NCI_CONTAINERREGISTRY_REPOSITORY}
   export CONTAINER_TAG=${CONTAINER_TAG:-$NCI_COMMIT_REF_RELEASE}
+
+  # support for SWARMSTACKFILE_DEFAULT
+  if ! test -f "$SWARMSTACKFILE"; then
+    act-log-message "no swarmstack file provided at [$SWARMSTACKFILE]" "DEBUG"
+
+    if [ -z "$SWARMSTACKFILE_DEFAULT" ]; then
+      act-log-message "no swarmstack file provided at [$SWARMSTACKFILE] and no default set using SWARMSTACKFILE_DEFAULT!" "ERROR"
+      exit 1
+    else
+      act-log-message "using default swarmstack file provided at [$SWARMSTACKFILE] from [$SWARMSTACKFILE_DEFAULT]!" "INFO"
+      curl -L -s -o "$SWARMSTACKFILE" "$SWARMSTACKFILE_DEFAULT"
+      USED_DEFAULT_SWARMCONFIG=true
+    fi
+  fi
 
   # generate deployment configuration
   act-common-deploy-generate-configuration $DEPLOYMENT_ENVIRONMENT
@@ -36,16 +62,15 @@ function main()
   act-common-container-registry-login
 
   # deploy stack (placeholders are replaced by the .env file provided to the stack file)
-  echo "-> run deployment [SWARM_ID:p${NCI_PROJECT_ID}-${DEPLOYMENT_ENVIRONMENT}] ..."
   set +e
   docker stack deploy --compose-file $SWARMSTACK_FILE --with-registry-auth $DEPLOYMENT_ID
   deploymentResult=$?
   set -e
   if [ "$deploymentResult" -ne "0" ]; then
-    echo "-> deployment failed ..."
-    exit 1
+    act-log-message "Failed to run deployment!" "ERROR"
+    exit $deploymentResult
   else
-    echo "-> deployment succeeded."
+    act-log-message "Deployment executed succesfully!" "INFO"
   fi
 }
 
@@ -61,7 +86,7 @@ case "${1:-}" in
     echo "* SWARMSTACK_FILE: provide a custom file with a docker swarm stack definition. (defaults to swarm.yml)"
     ;;
   *)
-    echo "Running action [$ACTION_CATEGORY.$ACTION_NAME]"
+    act-log-message "Running action [$ACTION_CATEGORY.$ACTION_NAME]" "INFO"
     act-common-prepare
     act-common-hook "pre-$ACTION_CATEGORY-$ACTION_NAME"
     main "$@"
diff --git a/stages/stage-deploy b/stages/stage-deploy
--- a/stages/stage-deploy
+++ b/stages/stage-deploy
@@ -9,51 +9,59 @@ source "$LOCAL_PATH/action-common"
 # main
 function main()
 {
+  act-log-message "Will deploy using method: ${DEPLOYMENT_TYPE}" "INFO"
+
   # deployment target: none
   if [[ ${DEPLOYMENT_TYPE} == "none" ]]; then
-    echo "-> not running deployment, no DEPLOYMENT_TYPE set!"
+    act-log-message "not running deployment, no DEPLOYMENT_TYPE set!" "NONE"
     exit 0
   fi
 
-  # deployment target
-  local DEPLOYMENT_ENVIRONMENT=${1:-}
-  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
-    echo "error: no target environment specified when calling deploy stage!"
+  # deployment namespace
+  local DEPLOYMENT_NAMESPACE=${1:-$DEPLOYMENT_NAMESPACE}
+  if [ -z "$DEPLOYMENT_NAMESPACE" ]; then
+    act-log-message "no target environment specified when calling deploy stage!" "ERROR"
     exit 1
   fi
-  local DEPLOYMENT_ID=${2:-p${NCI_PROJECT_ID}-${DEPLOYMENT_ENVIRONMENT}}
-  echo "-> deploying environment [$DEPLOYMENT_ENVIRONMENT] ..."
 
-  # by deployment type
+  # deployment id
+  local DEPLOYMENT_ID=${2:-$DEPLOYMENT_ID}
+
+  # deployment target
+  local DEPLOYMENT_ENVIRONMENT=${3:-$DEPLOYMENT_ENVIRONMENT}
+  if [ -z "$DEPLOYMENT_ENVIRONMENT" ]; then
+    act-log-message "no target environment specified when calling deploy stage!" "ERROR"
+    exit 1
+  fi
+
+  act-log-message "deploying environment [$DEPLOYMENT_ENVIRONMENT] ..." "INFO"
+
+  # deploymentType: docker swarm
   if [[ ${DEPLOYMENT_TYPE} == "swarm" ]]; then
-    echo "-> deployment will use swarm stacks ..."
-
-    # configuration
-    export SWARMSTACK_FILE=${SWARMSTACK_FILE:-swarm.yml}
-
-    # pull swarm stack by template
-    if [ ! -f $SWARMSTACK_FILE ]; then
-      # retrieve swarm stack template file by project type of the project didn't provide one
-      if [[ ${PROJECT_TYPE} =~ ^.*-service$ ]]; then
-        echo "-> download swarm template for build stack $PROJECT_TYPE and setting SWARMSTACK_FILE."
-        curl -L -s -o "dist/swarm-deployment.yml" "$MPI_RESOURCES_MIRROR/swarm-service.yml"
-        export SWARMSTACK_FILE=dist/swarm-deployment.yml
-      else
-        echo "error: project type $PROJECT_TYPE is not supported yet! Please request support or provide your own swarm.yml."
-        exit 1
-      fi
+    # web based services
+    if [[ ${PROJECT_TYPE} =~ ^.*-http$ ]]; then
+      export SWARMSTACKFILE_DEFAULT="$MPI_RESOURCES_MIRROR/swarm-http.yml"
     fi
 
     # run deployment
-    action-swarm-deploy $DEPLOYMENT_ENVIRONMENT $DEPLOYMENT_ID
-  elif [[ ${DEPLOYMENT_TYPE} == "helm" ]]; then
-    echo "-> deployment will use helm charts ..."
-
-    # run deployment
-    action-helm-deploy $DEPLOYMENT_ENVIRONMENT $DEPLOYMENT_ID
-  else
-    echo "warning: deployment type ${DEPLOYMENT_TYPE} is not supported!"
+    action-swarm-deploy "$DEPLOYMENT_NAMESPACE" "$DEPLOYMENT_ENVIRONMENT" "$DEPLOYMENT_ID"
+    exit 0
   fi
+
+  # deploymentType: helm
+  if [[ ${DEPLOYMENT_TYPE} == "helm" ]]; then
+    # web based services
+    if [[ ${PROJECT_TYPE} =~ ^.*-http$ ]]; then
+      DEPLOYMENT_CHART=philippheuer/webservice
+    fi
+
+    action-helm-deploy "$DEPLOYMENT_NAMESPACE" "$DEPLOYMENT_ENVIRONMENT" "$DEPLOYMENT_ID" "$DEPLOYMENT_CHART"
+    exit 0
+  fi
+
+  # no match
+  act-log-message "deployment type ${DEPLOYMENT_TYPE} is not supported!" "ERROR"
+  exit 1
 }
 
 # entrypoint
@@ -66,7 +74,7 @@ case "${1:-}" in
     echo "* DEBUG: Can be set to true to enable debugging"
     ;;
   *)
-    echo "Running stage [$STAGE_NAME]"
+    act-log-message "Running stage [$STAGE_NAME]" "INFO"
     act-common-prepare
     act-common-hook "pre-$STAGE_NAME"
     main "$@"
